extern void getInput(char *text, char *output, int strSize);
extern void nomChars(char *charArray, char *output);
extern void clearScreen();
extern void cursorManip(int io);
extern void getConfig(char *output, char mode);
extern void colourText(char *text, char colour);
extern void rainbow(char *text);
extern void echoIO(bool echoIsOn);
extern void enterToContinue();
extern void fileSize(char const filepath[]);
extern void typeWriter(char *string, int width, bool newline);